# -*- coding: utf-8 -*-
"""WEEK-6

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1arHaEbqbezSCXZLME4nTiMlRHvckSUnP
"""

import pandas as pd
import numpy as np

np.random.seed(42)
n = 100000

data = pd.DataFrame({
    "Customer_ID": np.arange(1, n+1),
    "Age": np.random.randint(18, 71, n),
    "Gender": np.random.choice(["Male", "Female"], n),
    "Tenure": np.random.randint(0, 11, n),
    "Balance": np.random.randint(0, 200001, n),
    "CreditScore": np.random.randint(300, 901, n),
    "EstimatedSalary": np.random.randint(10000, 150001, n),
    "NumOfProducts": np.random.randint(1, 5, n),
    "IsActiveMember": np.random.choice(["Yes", "No"], n)
})


data["Churn"] = np.where(
    (data["Balance"] < 50000) &
    (data["IsActiveMember"] == "No") &
    (data["Tenure"] < 3), 1, 0
)

print(data.head())

print(data.isnull().sum())

print(data.dtypes)

data.drop_duplicates(inplace=True)

data["Gender"] = data["Gender"].map({"Male": 0, "Female": 1})
data["IsActiveMember"] = data["IsActiveMember"].map({"No": 0, "Yes": 1})

print(data.mean(numeric_only=True))

print(data.median(numeric_only=True))

print(data.mode().iloc[0])

print(data.std(numeric_only=True))

high_churn = data[data["Churn"] == 1]
low_churn = data[data["Churn"] == 0]

print("High Churn Count:", len(high_churn))
print("Low Churn Count:", len(low_churn))

print(data.groupby("Churn").mean(numeric_only=True))

data["AgeGroup"] = pd.cut(data["Age"],
                         bins=[18,30,40,50,60,70],
                         labels=["18-30","31-40","41-50","51-60","61-70"])

print(data.groupby("AgeGroup")["Churn"].mean())

print(data.groupby("Gender")["Churn"].mean())

print(data.groupby("IsActiveMember")["Churn"].mean())

print(data.groupby("NumOfProducts")["Churn"].mean())

print(data.groupby("Churn")["Balance"].mean())

print(data.groupby("Churn")["CreditScore"].mean())

print(data.groupby("Churn")["Tenure"].mean())

import matplotlib.pyplot as plt
import seaborn as sns

sns.countplot(x="Churn", data=data)

plt.title("Churn Distribution")
plt.legend(["Count of Customers"])
plt.show()

data["Churn"].value_counts().plot.pie(
    autopct='%1.1f%%',
    labels=["No Churn", "Churn"]
)

plt.title("Churn Percentage")
plt.legend(["No Churn", "Churn"], loc="upper right")
plt.ylabel("")
plt.show()

plt.hist(data["Age"], bins=30, label="Age Distribution")

plt.title("Age Distribution")
plt.legend()
plt.show()

plt.scatter(data["Balance"], data["CreditScore"], alpha=0.3, label="Customers")

plt.xlabel("Balance")
plt.ylabel("Credit Score")
plt.title("Balance vs Credit Score")
plt.legend()
plt.show()

sns.boxplot(x="Churn", y="Balance", data=data)

plt.title("Balance vs Churn")
plt.legend(["Balance Distribution"])
plt.show()

heatmap = sns.heatmap(data.drop('AgeGroup', axis=1).corr(), annot=True, cmap="coolwarm")

plt.title("Correlation Heatmap")

# Add label to color bar (legend style)
cbar = heatmap.collections[0].colorbar
cbar.set_label("Correlation Strength")

plt.show()

print("Key Insights:")
print("1. Low balance + inactive customers → high churn")
print("2. Low tenure customers churn more")
print("3. Fewer products → higher churn")
print("4. Active users → lower churn")

print("Successfully")

